const products = [
  {
    id: 1,
    title: 'T-SHIRT WITH TAPE DETAILS',
    img: '/Images/image 7.png',
    price: 145,
    rating: 3.5,
    color: 'Black',
    size: ['M', 'L'],
    style: 'T-shirt',
  },
  {
    id: 2,
    title: 'SKINNY FIT JEANS',
    img: '/Images/image 8.png',
    price: 180,
    rating: 4.5,
    color: 'Blue',
    size: ['S', 'M', 'L'],
    style: 'Jeans',
  },
  {
    id: 3,
    title: 'CHECKERED SHIRT',
    img: '/Images/image 9.png',
    price: 150,
    discountPrice: 120,
    discount: 30,
    rating: 5.0,
    color: 'Red',
    size: ['S', 'M', 'XL'],
    style: 'Shirt',
  },
  {
    id: 4,
    title: 'SLEEVE STRIPED T-SHIRT',
    img: '/Images/image 10.png',
    price: 200,
    rating: 4.8,
    color: 'Red',
    size: ['M', 'L', 'XL'],
    style: 'T-shirt',
  },
  {
    id: 5,
    title: 'VERTICAL STRIPED SHIRT',
    img: '/Images/image 11.png',
    price: 130,
    rating: 4.2,
    color: 'Green',
    size: ['S', 'M'],
    style: 'Shirt',
  },
  {
    id: 6,
    title: 'COURAGE GRAPHIC T-SHIRT',
    img: '/Images/image 12.png',
    price: 160,
    discountPrice: 140,
    discount: 20,
    rating: 4.0,
    color: 'Yellow',
    size: ['M', 'L'],
    style: 'T-shirt',
  },
  {
    id: 7,
    title: 'LOOSE FIT BERMUDA SHORTS',
    img: '/Images/image 13.png',
    price: 110,
    rating: 3.8,
    color: 'Blue',
    size: ['XS', 'S', 'M'],
    style: 'Shorts',
  },
  {
    id: 8,
    title: 'FADED SKINNY JEANS',
    img: '/Images/image 14.png',
    price: 110,
    rating: 3.8,
    color: 'Black',
    size: ['XS', 'S', 'M'],
    style: 'Jeans',
  },
];

export default products;
