const products = [
  {
    id: 1,
    title: 'Gradient Graphic T-shirt',
    img: '/Images/image 7.png',
    price: 145,
    rating: 3.5,
    color: 'Blue',
    size: ['M', 'L'],
    style: 'T-shirt',
  },
  {
    id: 2,
    title: 'Polo with Tipping Details',
    img: '/Images/image 8.png',
    price: 180,
    rating: 4.5,
    color: 'White',
    size: ['S', 'M', 'L'],
    style: 'Shirt',
  },
  {
    id: 3,
    title: 'Black Striped T-shirt',
    img: '/Images/image 9.png',
    price: 150,
    discountPrice: 120,
    discount: 30,
    rating: 5.0,
    color: 'Black',
    size: ['S', 'M', 'XL'],
    style: 'Shorts',
  },
  {
    id: 4,
    title: 'Red Hoodie',
    img: '/Images/image 10.png',
    price: 200,
    rating: 4.8,
    color: 'Red',
    size: ['M', 'L', 'XL'],
    style: 'Hoodie',
  },
  {
    id: 5,
    title: 'Green Oversized T-shirt',
    img: '/Images/image 11.png',
    price: 130,
    rating: 4.2,
    color: 'Green',
    size: ['S', 'M'],
    style: 'Jeans',
  },
  {
    id: 6,
    title: 'Yellow Polo Shirt',
    img: '/Images/image 12.png',
    price: 160,
    discountPrice: 140,
    discount: 20,
    rating: 4.0,
    color: 'Yellow',
    size: ['M', 'L'],
    style: 'Shirt',
  },
  {
    id: 7,
    title: 'White Casual T-shirt',
    img: '/Images/image 13.png',
    price: 110,
    rating: 3.8,
    color: 'White',
    size: ['XS', 'S', 'M'],
    style: 'T-shirt',
  },
];

export default products;
